// <auto-generated />
using System;
using Diiage.Memoire.Back.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diiage.Memoire.Back.Persistence.Migration.Migrations
{
    [DbContext(typeof(DbContextCore))]
    [Migration("20250308171602_ProjectInitialization")]
    partial class ProjectInitialization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("diiage-memoire-core")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.Documents.DocumentDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("ThirdPartyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ThirdPartyId");

                    b.ToTable("Documents", "diiage-memoire-core");
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.Documents.DocumentRowDao", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.ToTable("DocumentRows", "diiage-memoire-core");
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.Tanks.AllowedVariables.AllowedVariableDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<int?>("TankDaoId")
                        .HasColumnType("int");

                    b.Property<int>("VariableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.HasIndex("TankDaoId");

                    b.HasIndex("VariableId");

                    b.ToTable("AllowedVariables", "diiage-memoire-core");

                    b.HasDiscriminator<int>("Kind");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.Tanks.TankDao", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TankFamilyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tanks", "diiage-memoire-core");
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.Tanks.TankFamilyDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentFamilyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentFamilyId");

                    b.ToTable("TankFamilies", "diiage-memoire-core");
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.ThirdParties.ThirdPartyDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThirdParties", "diiage-memoire-core");
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.Units.UnitDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units", "diiage-memoire-core");
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.Variables.VariableDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Variables", "diiage-memoire-core");
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.Tanks.AllowedVariables.AllowedVariableBooleanDao", b =>
                {
                    b.HasBaseType("Diiage.Memoire.Back.Domain.Entities.Tanks.AllowedVariables.AllowedVariableDao");

                    b.Property<bool>("Value")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.Tanks.AllowedVariables.AllowedVariableNumericDao", b =>
                {
                    b.HasBaseType("Diiage.Memoire.Back.Domain.Entities.Tanks.AllowedVariables.AllowedVariableDao");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasIndex("UnitId");

                    b.ToTable("AllowedVariables", "diiage-memoire-core", t =>
                        {
                            t.Property("Value")
                                .HasColumnName("AllowedVariableNumericDao_Value");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.Tanks.AllowedVariables.AllowedVariableStringDao", b =>
                {
                    b.HasBaseType("Diiage.Memoire.Back.Domain.Entities.Tanks.AllowedVariables.AllowedVariableDao");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("AllowedVariables", "diiage-memoire-core", t =>
                        {
                            t.Property("Value")
                                .HasColumnName("AllowedVariableStringDao_Value");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.Documents.DocumentDao", b =>
                {
                    b.HasOne("Diiage.Memoire.Back.Domain.Entities.ThirdParties.ThirdPartyDao", "ThirdParty")
                        .WithMany("Documents")
                        .HasForeignKey("ThirdPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThirdParty");
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.Documents.DocumentRowDao", b =>
                {
                    b.HasOne("Diiage.Memoire.Back.Domain.Entities.Documents.DocumentDao", "Document")
                        .WithMany("Rows")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diiage.Memoire.Back.Domain.Entities.Tanks.TankDao", "Tank")
                        .WithMany()
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.Tanks.AllowedVariables.AllowedVariableDao", b =>
                {
                    b.HasOne("Diiage.Memoire.Back.Domain.Entities.Tanks.TankDao", null)
                        .WithMany("AllowedVariables")
                        .HasForeignKey("TankDaoId");

                    b.HasOne("Diiage.Memoire.Back.Domain.Entities.Variables.VariableDao", "Variable")
                        .WithMany()
                        .HasForeignKey("VariableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Variable");
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.Tanks.TankDao", b =>
                {
                    b.HasOne("Diiage.Memoire.Back.Domain.Entities.Tanks.TankFamilyDao", "TankFamily")
                        .WithMany("Tanks")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TankFamily");
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.Tanks.TankFamilyDao", b =>
                {
                    b.HasOne("Diiage.Memoire.Back.Domain.Entities.Tanks.TankFamilyDao", "ParentFamily")
                        .WithMany("ChildrenFamilies")
                        .HasForeignKey("ParentFamilyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentFamily");
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.Tanks.AllowedVariables.AllowedVariableNumericDao", b =>
                {
                    b.HasOne("Diiage.Memoire.Back.Domain.Entities.Units.UnitDao", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.Documents.DocumentDao", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.Tanks.TankDao", b =>
                {
                    b.Navigation("AllowedVariables");
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.Tanks.TankFamilyDao", b =>
                {
                    b.Navigation("ChildrenFamilies");

                    b.Navigation("Tanks");
                });

            modelBuilder.Entity("Diiage.Memoire.Back.Domain.Entities.ThirdParties.ThirdPartyDao", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
