<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Diiage.Memoire.Repositories</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Mapster" Version="7.4.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
        <PackageReference Include="Thinktecture.EntityFrameworkCore.SqlServer" Version="8.1.1" />
    </ItemGroup>

</Project>
