<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Diiage.Memoire.Back.Persistence.Migration</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Migrations\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Diiage.Memoire.Back.Persistence\Diiage.Memoire.Back.Persistence.csproj" />
    </ItemGroup>

</Project>
